title: Tashima42 Blog
description: 'Integrations, Development, Linux, etc. Tech stuff in general'
social_link: twitter
social_username: tashima42
github_repo: tashima42_blog
github_username: tashima42
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /tashima42_blog
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
